/*
 * Verbatim AI API
 * **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____
 *
 * The version of the OpenAPI document: v1
 * Contact: api@verbatim.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.api;

import com.verbatim.client.spring_rest.models.Corpus;
import com.verbatim.client.spring_rest.models.CorpusMetadata;
import com.verbatim.client.spring_rest.models.Error;
import com.verbatim.client.spring_rest.models.PageCorpus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CorpusApi
 */
@Disabled
class CorpusApiTest {

    private final CorpusApi api = new CorpusApi();

    
    /**
     * Create a new corpus
     *
     * Create a new corpus where your documents will be stored
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void add1Test() {
        CorpusMetadata corpusMetadata = null;

        Corpus response = api.add1(corpusMetadata);

        // TODO: test validations
    }
    
    /**
     * Delete a Corpus
     *
     * Permanent removal of a Corpus. No restore after a delete.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void delete1Test() {
        String corpusId = null;

        api.delete1(corpusId);

        // TODO: test validations
    }
    
    /**
     * Get a Corpus
     *
     * Get detail info about a Corpus
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void get1Test() {
        String corpusId = null;

        Corpus response = api.get1(corpusId);

        // TODO: test validations
    }
    
    /**
     * List corpus
     *
     * List your corpus
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void list2Test() {
        String pageToken = null;
        Integer pageSize = null;

        PageCorpus response = api.list2(pageToken, pageSize);

        // TODO: test validations
    }
    
    /**
     * Update metadata of a Corpus
     *
     * Update display info of your corpus
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void update1Test() {
        String corpusId = null;
        CorpusMetadata corpusMetadata = null;

        Corpus response = api.update1(corpusId, corpusMetadata);

        // TODO: test validations
    }
    
}
