/*
 * Verbatim AI API
 * **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____
 *
 * The version of the OpenAPI document: v1
 * Contact: api@verbatim.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.api;

import com.verbatim.client.spring_rest.models.Crawler;
import com.verbatim.client.spring_rest.models.CrawlerMetadata;
import com.verbatim.client.spring_rest.models.Error;
import com.verbatim.client.spring_rest.models.PageCrawler;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CrawlerApi
 */
@Disabled
class CrawlerApiTest {

    private final CrawlerApi api = new CrawlerApi();

    
    /**
     * Create a new crawler
     *
     * Create a new crawler. Only available if account has been init and attached to an organization
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void addTest() {
        String corpusId = null;
        CrawlerMetadata crawlerMetadata = null;

        Crawler response = api.add(corpusId, crawlerMetadata);

        // TODO: test validations
    }
    
    /**
     * Delete a crawler
     *
     * Permanent removal of a crawler. No restore after a delete
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void deleteTest() {
        String corpusId = null;
        String crawlerId = null;

        api.delete(corpusId, crawlerId);

        // TODO: test validations
    }
    
    /**
     * Get a crawler
     *
     * Get detail info about a Crawler
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void getTest() {
        String corpusId = null;
        String crawlerId = null;

        Crawler response = api.get(corpusId, crawlerId);

        // TODO: test validations
    }
    
    /**
     * List the crawler
     *
     * List your crawlers
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void list1Test() {
        String corpusId = null;
        String pageToken = null;
        Integer pageSize = null;

        PageCrawler response = api.list1(corpusId, pageToken, pageSize);

        // TODO: test validations
    }
    
    /**
     * Update metadata of a Crawler
     *
     * Update display info of your crawler
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void updateTest() {
        String corpusId = null;
        String crawlerId = null;
        CrawlerMetadata crawlerMetadata = null;

        Crawler response = api.update(corpusId, crawlerId, crawlerMetadata);

        // TODO: test validations
    }
    
}
