/*
 * Verbatim AI API
 * **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____
 *
 * The version of the OpenAPI document: v1
 * Contact: api@verbatim.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Crawler
 */
@JsonPropertyOrder({
  Crawler.JSON_PROPERTY_DISPLAY_NAME,
  Crawler.JSON_PROPERTY_DESCRIPTION,
  Crawler.JSON_PROPERTY_URL,
  Crawler.JSON_PROPERTY_MAX_CRAWL_DEPTH,
  Crawler.JSON_PROPERTY_ENABLED,
  Crawler.JSON_PROPERTY_CREATED_AT,
  Crawler.JSON_PROPERTY_UPDATED_AT,
  Crawler.JSON_PROPERTY_ID,
  Crawler.JSON_PROPERTY_CORPUS_ID,
  Crawler.JSON_PROPERTY_NEXT_CRAWL,
  Crawler.JSON_PROPERTY_LAST_CRAWL,
  Crawler.JSON_PROPERTY_NB_DOC,
  Crawler.JSON_PROPERTY_SIZE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Crawler {
  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  @javax.annotation.Nonnull
  private String displayName;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nonnull
  private String url;

  public static final String JSON_PROPERTY_MAX_CRAWL_DEPTH = "maxCrawlDepth";
  @javax.annotation.Nullable
  private Integer maxCrawlDepth;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_CORPUS_ID = "corpusId";
  @javax.annotation.Nullable
  private String corpusId;

  public static final String JSON_PROPERTY_NEXT_CRAWL = "nextCrawl";
  @javax.annotation.Nullable
  private OffsetDateTime nextCrawl;

  public static final String JSON_PROPERTY_LAST_CRAWL = "lastCrawl";
  @javax.annotation.Nullable
  private OffsetDateTime lastCrawl;

  public static final String JSON_PROPERTY_NB_DOC = "nbDoc";
  @javax.annotation.Nullable
  private Integer nbDoc;

  public static final String JSON_PROPERTY_SIZE = "size";
  @javax.annotation.Nullable
  private Long size;

  public Crawler() {
  }

  public Crawler displayName(@javax.annotation.Nonnull String displayName) {
    
    this.displayName = displayName;
    return this;
  }

  /**
   * Display name of your Crawler
   * @return displayName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayName(@javax.annotation.Nonnull String displayName) {
    this.displayName = displayName;
  }

  public Crawler description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Description of your Crawler
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public Crawler url(@javax.annotation.Nonnull String url) {
    
    this.url = url;
    return this;
  }

  /**
   * Root url of the domain the crawl. Must start with http// or https://
   * @return url
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@javax.annotation.Nonnull String url) {
    this.url = url;
  }

  public Crawler maxCrawlDepth(@javax.annotation.Nullable Integer maxCrawlDepth) {
    
    this.maxCrawlDepth = maxCrawlDepth;
    return this;
  }

  /**
   * Maximum crawl depth
   * maximum: 5
   * @return maxCrawlDepth
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAX_CRAWL_DEPTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxCrawlDepth() {
    return maxCrawlDepth;
  }


  @JsonProperty(JSON_PROPERTY_MAX_CRAWL_DEPTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxCrawlDepth(@javax.annotation.Nullable Integer maxCrawlDepth) {
    this.maxCrawlDepth = maxCrawlDepth;
  }

  public Crawler enabled(@javax.annotation.Nullable Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

  /**
   * Activation state of the crawler. True, the crawler is enable and have recurrent crawl schedule. False, the crawler is disable, no crawl until is back to an enable state.
   * @return enabled
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(JSON_PROPERTY_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }

  public Crawler createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Crawler updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Crawler id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * ID of the crawler. Primary key use to index this crawler
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public Crawler corpusId(@javax.annotation.Nullable String corpusId) {
    
    this.corpusId = corpusId;
    return this;
  }

  /**
   * ID of the corpus where the crawler is attached
   * @return corpusId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CORPUS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCorpusId() {
    return corpusId;
  }


  @JsonProperty(JSON_PROPERTY_CORPUS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCorpusId(@javax.annotation.Nullable String corpusId) {
    this.corpusId = corpusId;
  }

  public Crawler nextCrawl(@javax.annotation.Nullable OffsetDateTime nextCrawl) {
    
    this.nextCrawl = nextCrawl;
    return this;
  }

  /**
   * Get nextCrawl
   * @return nextCrawl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEXT_CRAWL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getNextCrawl() {
    return nextCrawl;
  }


  @JsonProperty(JSON_PROPERTY_NEXT_CRAWL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextCrawl(@javax.annotation.Nullable OffsetDateTime nextCrawl) {
    this.nextCrawl = nextCrawl;
  }

  public Crawler lastCrawl(@javax.annotation.Nullable OffsetDateTime lastCrawl) {
    
    this.lastCrawl = lastCrawl;
    return this;
  }

  /**
   * Get lastCrawl
   * @return lastCrawl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_CRAWL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastCrawl() {
    return lastCrawl;
  }


  @JsonProperty(JSON_PROPERTY_LAST_CRAWL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastCrawl(@javax.annotation.Nullable OffsetDateTime lastCrawl) {
    this.lastCrawl = lastCrawl;
  }

  public Crawler nbDoc(@javax.annotation.Nullable Integer nbDoc) {
    
    this.nbDoc = nbDoc;
    return this;
  }

  /**
   * Number of document crawler by the crawler. Merged into your quota
   * @return nbDoc
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NB_DOC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNbDoc() {
    return nbDoc;
  }


  @JsonProperty(JSON_PROPERTY_NB_DOC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNbDoc(@javax.annotation.Nullable Integer nbDoc) {
    this.nbDoc = nbDoc;
  }

  public Crawler size(@javax.annotation.Nullable Long size) {
    
    this.size = size;
    return this;
  }

  /**
   * Storage size use by the crawler.  Merged into your quota
   * @return size
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSize() {
    return size;
  }


  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSize(@javax.annotation.Nullable Long size) {
    this.size = size;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Crawler crawler = (Crawler) o;
    return Objects.equals(this.displayName, crawler.displayName) &&
        Objects.equals(this.description, crawler.description) &&
        Objects.equals(this.url, crawler.url) &&
        Objects.equals(this.maxCrawlDepth, crawler.maxCrawlDepth) &&
        Objects.equals(this.enabled, crawler.enabled) &&
        Objects.equals(this.createdAt, crawler.createdAt) &&
        Objects.equals(this.updatedAt, crawler.updatedAt) &&
        Objects.equals(this.id, crawler.id) &&
        Objects.equals(this.corpusId, crawler.corpusId) &&
        Objects.equals(this.nextCrawl, crawler.nextCrawl) &&
        Objects.equals(this.lastCrawl, crawler.lastCrawl) &&
        Objects.equals(this.nbDoc, crawler.nbDoc) &&
        Objects.equals(this.size, crawler.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, description, url, maxCrawlDepth, enabled, createdAt, updatedAt, id, corpusId, nextCrawl, lastCrawl, nbDoc, size);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Crawler {\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    maxCrawlDepth: ").append(toIndentedString(maxCrawlDepth)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    corpusId: ").append(toIndentedString(corpusId)).append("\n");
    sb.append("    nextCrawl: ").append(toIndentedString(nextCrawl)).append("\n");
    sb.append("    lastCrawl: ").append(toIndentedString(lastCrawl)).append("\n");
    sb.append("    nbDoc: ").append(toIndentedString(nbDoc)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

