/*
 * Verbatim AI API
 * **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____
 *
 * The version of the OpenAPI document: v1
 * Contact: api@verbatim.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.verbatim.client.spring_rest.api;

import cloud.verbatim.client.spring_rest.models.Error;
import cloud.verbatim.client.spring_rest.models.TokenInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticateApi
 */
@Disabled
class AuthenticateApiTest {

    private final AuthenticateApi api = new AuthenticateApi();

    
    /**
     * Info about the token used for authenticated this query
     *
     * Get info about the active session (token)
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void whoamiTest() {

        TokenInfo response = api.whoami();

        // TODO: test validations
    }
    
}
