/*
 * Verbatim AI API
 * **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____
 *
 * The version of the OpenAPI document: v1
 * Contact: api@verbatim.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.verbatim.client.spring_rest.api;

import cloud.verbatim.client.spring_rest.models.Error;
import cloud.verbatim.client.spring_rest.models.PromptResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PromptApi
 */
@Disabled
class PromptApiTest {

    private final PromptApi api = new PromptApi();

    
    /**
     * Run a prompt
     *
     * Your prompt is process in the engine. Semantic response if give in the body with attachments found from your corpus
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void promptTest() {
        String corpusId = null;
        String model = null;
        String query = null;

        PromptResponse response = api.prompt(corpusId, model, query);

        // TODO: test validations
    }
    
}
