/*
 * Verbatim AI API
 * **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____
 *
 * The version of the OpenAPI document: v1
 * Contact: api@verbatim.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Crawler
 */
class CrawlerTest {
    private final Crawler model = new Crawler();

    /**
     * Model tests for Crawler
     */
    @Test
    void testCrawler() {
        // TODO: test Crawler
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'url'
     */
    @Test
    void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'maxCrawlDepth'
     */
    @Test
    void maxCrawlDepthTest() {
        // TODO: test maxCrawlDepth
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'corpusId'
     */
    @Test
    void corpusIdTest() {
        // TODO: test corpusId
    }

    /**
     * Test the property 'nextCrawl'
     */
    @Test
    void nextCrawlTest() {
        // TODO: test nextCrawl
    }

    /**
     * Test the property 'lastCrawl'
     */
    @Test
    void lastCrawlTest() {
        // TODO: test lastCrawl
    }

    /**
     * Test the property 'nbDoc'
     */
    @Test
    void nbDocTest() {
        // TODO: test nbDoc
    }

    /**
     * Test the property 'size'
     */
    @Test
    void sizeTest() {
        // TODO: test size
    }

}
