/*
 * Verbatim AI API
 * **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____
 *
 * The version of the OpenAPI document: v1
 * Contact: api@verbatim.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.verbatim.client.spring_rest.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.verbatim.client.spring_rest.models.PromptDocumentAttachment;
import com.verbatim.client.spring_rest.models.PromptPart;
import com.verbatim.client.spring_rest.models.PromptWebAttachment;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PromptResponse
 */
class PromptResponseTest {
    private final PromptResponse model = new PromptResponse();

    /**
     * Model tests for PromptResponse
     */
    @Test
    void testPromptResponse() {
        // TODO: test PromptResponse
    }

    /**
     * Test the property 'issuedAt'
     */
    @Test
    void issuedAtTest() {
        // TODO: test issuedAt
    }

    /**
     * Test the property 'corpusId'
     */
    @Test
    void corpusIdTest() {
        // TODO: test corpusId
    }

    /**
     * Test the property 'query'
     */
    @Test
    void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'text'
     */
    @Test
    void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'parts'
     */
    @Test
    void partsTest() {
        // TODO: test parts
    }

    /**
     * Test the property 'document'
     */
    @Test
    void documentTest() {
        // TODO: test document
    }

    /**
     * Test the property 'web'
     */
    @Test
    void webTest() {
        // TODO: test web
    }

}
