/*
 * Verbatim AI API
 * **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____
 *
 * The version of the OpenAPI document: v1
 * Contact: api@verbatim.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.verbatim.client.spring_rest.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TokenInfo
 */
class TokenInfoTest {
    private final TokenInfo model = new TokenInfo();

    /**
     * Model tests for TokenInfo
     */
    @Test
    void testTokenInfo() {
        // TODO: test TokenInfo
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'issuedAt'
     */
    @Test
    void issuedAtTest() {
        // TODO: test issuedAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'organizationId'
     */
    @Test
    void organizationIdTest() {
        // TODO: test organizationId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'keyId'
     */
    @Test
    void keyIdTest() {
        // TODO: test keyId
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'emailVerified'
     */
    @Test
    void emailVerifiedTest() {
        // TODO: test emailVerified
    }

}
