/*
 * Verbatim AI API
 * **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____
 *
 * The version of the OpenAPI document: v1
 * Contact: api@verbatim.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.verbatim.client.spring_rest.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DocumentSign
 */
@JsonPropertyOrder({
  DocumentSign.JSON_PROPERTY_DOCUMENT_ID,
  DocumentSign.JSON_PROPERTY_SIGN_URL,
  DocumentSign.JSON_PROPERTY_EXPIRED_AT,
  DocumentSign.JSON_PROPERTY_CREATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class DocumentSign {
  public static final String JSON_PROPERTY_DOCUMENT_ID = "documentId";
  @javax.annotation.Nullable
  private String documentId;

  public static final String JSON_PROPERTY_SIGN_URL = "signUrl";
  @javax.annotation.Nullable
  private String signUrl;

  public static final String JSON_PROPERTY_EXPIRED_AT = "expiredAt";
  @javax.annotation.Nullable
  private OffsetDateTime expiredAt;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public DocumentSign() {
  }

  public DocumentSign documentId(@javax.annotation.Nullable String documentId) {
    
    this.documentId = documentId;
    return this;
  }

  /**
   * ID of the document
   * @return documentId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocumentId() {
    return documentId;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentId(@javax.annotation.Nullable String documentId) {
    this.documentId = documentId;
  }

  public DocumentSign signUrl(@javax.annotation.Nullable String signUrl) {
    
    this.signUrl = signUrl;
    return this;
  }

  /**
   * Secured url to access your doc
   * @return signUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSignUrl() {
    return signUrl;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignUrl(@javax.annotation.Nullable String signUrl) {
    this.signUrl = signUrl;
  }

  public DocumentSign expiredAt(@javax.annotation.Nullable OffsetDateTime expiredAt) {
    
    this.expiredAt = expiredAt;
    return this;
  }

  /**
   * Timestamp when signed URL will expire. Your signUrl can&#39;t be used any more after this date.
   * @return expiredAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getExpiredAt() {
    return expiredAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiredAt(@javax.annotation.Nullable OffsetDateTime expiredAt) {
    this.expiredAt = expiredAt;
  }

  public DocumentSign createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Timestamp when signed url has been emit.
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentSign documentSign = (DocumentSign) o;
    return Objects.equals(this.documentId, documentSign.documentId) &&
        Objects.equals(this.signUrl, documentSign.signUrl) &&
        Objects.equals(this.expiredAt, documentSign.expiredAt) &&
        Objects.equals(this.createdAt, documentSign.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, signUrl, expiredAt, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentSign {\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    signUrl: ").append(toIndentedString(signUrl)).append("\n");
    sb.append("    expiredAt: ").append(toIndentedString(expiredAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

