/*
 * Verbatim AI API
 * **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____
 *
 * The version of the OpenAPI document: v1
 * Contact: api@verbatim.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.verbatim.client.spring_rest.models;

import java.util.Objects;
import java.util.Arrays;
import cloud.verbatim.client.spring_rest.models.PromptDocumentAttachment;
import cloud.verbatim.client.spring_rest.models.PromptPart;
import cloud.verbatim.client.spring_rest.models.PromptWebAttachment;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PromptResponse
 */
@JsonPropertyOrder({
  PromptResponse.JSON_PROPERTY_ISSUED_AT,
  PromptResponse.JSON_PROPERTY_CORPUS_ID,
  PromptResponse.JSON_PROPERTY_QUERY,
  PromptResponse.JSON_PROPERTY_TEXT,
  PromptResponse.JSON_PROPERTY_PARTS,
  PromptResponse.JSON_PROPERTY_DOCUMENT,
  PromptResponse.JSON_PROPERTY_WEB
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class PromptResponse {
  public static final String JSON_PROPERTY_ISSUED_AT = "issuedAt";
  @javax.annotation.Nullable
  private OffsetDateTime issuedAt;

  public static final String JSON_PROPERTY_CORPUS_ID = "corpusId";
  @javax.annotation.Nullable
  private String corpusId;

  public static final String JSON_PROPERTY_QUERY = "query";
  @javax.annotation.Nullable
  private String query;

  public static final String JSON_PROPERTY_TEXT = "text";
  @javax.annotation.Nullable
  private String text;

  public static final String JSON_PROPERTY_PARTS = "parts";
  @javax.annotation.Nullable
  private List<PromptPart> parts = new ArrayList<>();

  public static final String JSON_PROPERTY_DOCUMENT = "document";
  @javax.annotation.Nullable
  private List<PromptDocumentAttachment> document = new ArrayList<>();

  public static final String JSON_PROPERTY_WEB = "web";
  @javax.annotation.Nullable
  private List<PromptWebAttachment> web = new ArrayList<>();

  public PromptResponse() {
  }

  public PromptResponse issuedAt(@javax.annotation.Nullable OffsetDateTime issuedAt) {
    
    this.issuedAt = issuedAt;
    return this;
  }

  /**
   * Get issuedAt
   * @return issuedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ISSUED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getIssuedAt() {
    return issuedAt;
  }


  @JsonProperty(JSON_PROPERTY_ISSUED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuedAt(@javax.annotation.Nullable OffsetDateTime issuedAt) {
    this.issuedAt = issuedAt;
  }

  public PromptResponse corpusId(@javax.annotation.Nullable String corpusId) {
    
    this.corpusId = corpusId;
    return this;
  }

  /**
   * Get corpusId
   * @return corpusId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CORPUS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCorpusId() {
    return corpusId;
  }


  @JsonProperty(JSON_PROPERTY_CORPUS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCorpusId(@javax.annotation.Nullable String corpusId) {
    this.corpusId = corpusId;
  }

  public PromptResponse query(@javax.annotation.Nullable String query) {
    
    this.query = query;
    return this;
  }

  /**
   * Your query
   * @return query
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQuery() {
    return query;
  }


  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuery(@javax.annotation.Nullable String query) {
    this.query = query;
  }

  public PromptResponse text(@javax.annotation.Nullable String text) {
    
    this.text = text;
    return this;
  }

  /**
   * Generative AI Agent answer to your query
   * @return text
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }

  public PromptResponse parts(@javax.annotation.Nullable List<PromptPart> parts) {
    
    this.parts = parts;
    return this;
  }

  public PromptResponse addPartsItem(PromptPart partsItem) {
    if (this.parts == null) {
      this.parts = new ArrayList<>();
    }
    this.parts.add(partsItem);
    return this;
  }

  /**
   * Get parts
   * @return parts
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PromptPart> getParts() {
    return parts;
  }


  @JsonProperty(JSON_PROPERTY_PARTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParts(@javax.annotation.Nullable List<PromptPart> parts) {
    this.parts = parts;
  }

  public PromptResponse document(@javax.annotation.Nullable List<PromptDocumentAttachment> document) {
    
    this.document = document;
    return this;
  }

  public PromptResponse addDocumentItem(PromptDocumentAttachment documentItem) {
    if (this.document == null) {
      this.document = new ArrayList<>();
    }
    this.document.add(documentItem);
    return this;
  }

  /**
   * Get document
   * @return document
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PromptDocumentAttachment> getDocument() {
    return document;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocument(@javax.annotation.Nullable List<PromptDocumentAttachment> document) {
    this.document = document;
  }

  public PromptResponse web(@javax.annotation.Nullable List<PromptWebAttachment> web) {
    
    this.web = web;
    return this;
  }

  public PromptResponse addWebItem(PromptWebAttachment webItem) {
    if (this.web == null) {
      this.web = new ArrayList<>();
    }
    this.web.add(webItem);
    return this;
  }

  /**
   * Get web
   * @return web
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PromptWebAttachment> getWeb() {
    return web;
  }


  @JsonProperty(JSON_PROPERTY_WEB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeb(@javax.annotation.Nullable List<PromptWebAttachment> web) {
    this.web = web;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromptResponse promptResponse = (PromptResponse) o;
    return Objects.equals(this.issuedAt, promptResponse.issuedAt) &&
        Objects.equals(this.corpusId, promptResponse.corpusId) &&
        Objects.equals(this.query, promptResponse.query) &&
        Objects.equals(this.text, promptResponse.text) &&
        Objects.equals(this.parts, promptResponse.parts) &&
        Objects.equals(this.document, promptResponse.document) &&
        Objects.equals(this.web, promptResponse.web);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuedAt, corpusId, query, text, parts, document, web);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromptResponse {\n");
    sb.append("    issuedAt: ").append(toIndentedString(issuedAt)).append("\n");
    sb.append("    corpusId: ").append(toIndentedString(corpusId)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    parts: ").append(toIndentedString(parts)).append("\n");
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    web: ").append(toIndentedString(web)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

